printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
trailingComma: none
bracketSpacing: true
arrowParens: always
overrides:
  - files: "*.css"
    options:
      singleQuote: false
